version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 10
    reviewers:
      - "btasarimambalaj-afk"
    labels:
      - "dependencies"
      - "security"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    ignore:
      # Ignore major version updates for stable packages
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    # Group updates
    groups:
      production-dependencies:
        patterns:
          - "express*"
          - "socket.io*"
          - "helmet"
          - "cors"
        update-types:
          - "minor"
          - "patch"
      development-dependencies:
        patterns:
          - "@playwright/*"
          - "jest"
          - "eslint"
          - "prettier"
        update-types:
          - "minor"
          - "patch"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "ci/cd"
      - "dependencies"
    commit-message:
      prefix: "ci"
