services:
  - type: web
    name: adminara
    env: node
    region: frankfurt
    plan: free
    buildCommand: npm ci --only=production
    startCommand: node server.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: SESSION_SECRET
        generateValue: true
      - key: COOKIE_SECRET
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      - key: PUBLIC_URL
        sync: false
      - key: RENDER_EXTERNAL_URL
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_ADMIN_CHAT_ID
        sync: false
      - key: TURN_SERVER_URL
        sync: false
      - key: TURN_SECRET
        sync: false
      - key: REDIS_URL
        sync: false
      - key: SENTRY_DSN
        sync: false
      - key: METRICS_AUTH
        value: Basic YWRtaW46c2VjcmV0
      - key: ALLOWED_ORIGINS
        sync: false
      - key: ALLOWED_METRICS_ORIGINS
        sync: false
      - key: ENABLE_CSRF
        value: true
      - key: ENABLE_PII_MASKING
        value: true
      - key: PING_INTERVAL
        value: 240000
