name: Deploy to Production

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Deploy to Render
        run: |
          echo "Deploying to Render.com..."
          echo "Render auto-deploys on push to main branch"
          echo "Version: ${{ github.sha }}"
      
      - name: Notify deployment
        if: success()
        run: |
          echo "✅ Deployment successful"
          echo "Live URL: https://adminara.onrender.com"
      
      - name: Notify failure
        if: failure()
        run: echo "❌ Deployment failed"
