name: Security Scan

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'

jobs:
  dependency-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm ci
      - run: npm audit --audit-level=critical || true
      - name: Check for direct dependency vulnerabilities
        run: |
          echo "Checking direct dependencies only..."
          npm audit --json > audit.json || true
          node -e "
          const audit = require('./audit.json');
          const directVulns = Object.values(audit.vulnerabilities || {}).filter(v => v.isDirect);
          const critical = directVulns.filter(v => v.severity === 'critical');
          if (critical.length > 0) {
            console.error('Critical vulnerabilities in direct dependencies:', critical);
            process.exit(1);
          }
          console.log('No critical vulnerabilities in direct dependencies');
          "
